src/Entity/Address.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AddressRepository")
 */
class Address
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $street_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip_code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $more_information;



    public function getId(): ?int
    {
        return $this->id;
    }
    public function __toString()
    {
        return $this->city;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStreetName(): ?string
    {
        return $this->street_name;
    }

    public function setStreetName(string $street_name): self
    {
        $this->street_name = $street_name;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getMoreInformation(): ?string
    {
        return $this->more_information;
    }

    public function setMoreInformation(?string $more_information): self
    {
        $this->more_information = $more_information;

        return $this;
    }

  
}

src/Entity/Order.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderRepository")
 * @ORM\Table(name="`order`")
 * @ApiResource()
 */
class Order
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code_number;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $price;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Address")
     */
    private $shipping_address;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Address")
     */
    private $billing_address;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="orders")
     */
    private $seller;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="orders")
     */
    private $buyer;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\OrderProduct", mappedBy="myOrder")
     */
    private $orderProduct;

    public function __construct()
    {
        $this->orderProduct = new ArrayCollection();
    }
    public function __toString()
    {
        return $this->code_number;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodeNumber(): ?string
    {
        return $this->code_number;
    }

    public function setCodeNumber(string $code_number): self
    {
        $this->code_number = $code_number;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getShippingAddress(): ?Address
    {
        return $this->shipping_address;
    }

    public function setShippingAddress(?Address $shipping_address): self
    {
        $this->shipping_address = $shipping_address;

        return $this;
    }

    public function getBillingAddress(): ?Address
    {
        return $this->billing_address;
    }

    public function setBillingAddress(?Address $billing_address): self
    {
        $this->billing_address = $billing_address;

        return $this;
    }

    public function getSeller(): ?User
    {
        return $this->seller;
    }

    public function setSeller(?User $seller): self
    {
        $this->seller = $seller;

        return $this;
    }

    public function getBuyer(): ?User
    {
        return $this->buyer;
    }

    public function setBuyer(?User $buyer): self
    {
        $this->buyer = $buyer;

        return $this;
    }

    

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return Collection|OrderProduct[]
     */
    public function getOrderProduct(): Collection
    {
        return $this->orderProduct;
    }

    public function addOrderProduct(OrderProduct $orderProduct): self
    {
        if (!$this->orderProduct->contains($orderProduct)) {
            $this->orderProduct[] = $orderProduct;
            $orderProduct->setMyOrder($this);
        }

        return $this;
    }

    public function removeOrderProduct(OrderProduct $orderProduct): self
    {
        if ($this->orderProduct->contains($orderProduct)) {
            $this->orderProduct->removeElement($orderProduct);
            // set the owning side to null (unless already changed)
            if ($orderProduct->getMyOrder() === $this) {
                $orderProduct->setMyOrder(null);
            }
        }

        return $this;
    }
}

src/Form/OrderType.php
<?php

namespace App\Form;

use App\Entity\Order;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('code_number')
            ->add('price')
            ->add('shipping_address')
            ->add('billing_address')
            ->add('seller')
            ->add('buyer')
            ->add('orderProduct')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Order::class,
        ]);
    }
}

src/Controller/OrderController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\OrderType;
use App\Repository\OrderRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/order")
 */
class OrderController extends AbstractController
{
    /**
     * @Route("/admin", name="order_index", methods={"GET"})
     */
    public function index(OrderRepository $orderRepository): Response
    {
        return $this->render('order/index.html.twig', [
            'orders' => $orderRepository->findAll(),
        ]);
    }
    /**
     * @Route("/", name="order", methods={"GET"})
     */
    public function order(OrderRepository $orderRepository): Response
    {
        return $this->render('order/custom_show.html.twig', [
            'orders' => $orderRepository->findBy(["buyer" => $this->getUser()]),
        ]);
    }

    /**
     * @Route("/my", name="myorder", methods={"GET"})
     */
    public function myorder(OrderRepository $orderRepository): Response
    {
        return $this->render('order/order_as_seller.html.twig', [
            'orders' => $orderRepository->findBy(["seller" => $this->getUser()]),
        ]);
    }
    /**
     * @Route("/new", name="order_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $order = new Order();
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($order);
            $entityManager->flush();

            return $this->redirectToRoute('order_index');
        }

        return $this->render('order/new.html.twig', [
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="order_show", methods={"GET"})
     */
    public function show(Order $order): Response
    {
        return $this->render('order/show.html.twig', [
            'order' => $order,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="order_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Order $order): Response
    {
        $form = $this->createForm(OrderType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('order_index');
        }

        return $this->render('order/edit.html.twig', [
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }



    /**
     * @Route("/{id}", name="order_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Order $order): Response
    {
        if ($this->isCsrfTokenValid('delete' . $order->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('order_index');
    }

    /**
     * @Route("/{id}", name="change_status", methods={"POST"})
     */
    public function changeStatus(Request $request, Order $order): Response
    {
        $entityManager = $this->getDoctrine()->getManager();
        $order->setStatus($request->request->get('_status'));

        $entityManager->persist($order);
        $entityManager->flush();

        return $this->redirectToRoute('myorder');
    }
}

templates/order/_change_status_form.html.twig
<form method="post" action="{{ path('change_status', {'id': order.id}) }}" onsubmit="return confirm('Confirmez vous son nouveau status?');">
	<input type="hidden" name="_method" value="POST">
	<div class="form-group form-group-lg">
		<select id="status" class="form-control col-md-3" name="_status">
			<option {{ order.status == 'WAITING_CONFIRM' ? 'selected' }} value="WAITING_CONFIRM">En Attente de confirmation</option>
			<option {{ order.status == 'SEND' ? 'selected' }} value="SEND">Envoyé</option>
			<option {{ order.status == 'RECEIVE' ? 'selected' }} value="RECEIVE">Réceptionné</option>
		</select>
		<button class="btn btn-warning ">Confirmer</button>
	</div>
</form>

templates/order/_delete_form.html.twig
<form method="post" action="{{ path('order_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/order/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/order/custom_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order
{% endblock %}

{% block body %}
	<h1>Mes commandes
	</h1>
	{% for order in orders %}
		<div class="card p-3 mb-2 border rounded border-dark">
			<div class="mb-3">
				<h6>Commande n°{{ order.codeNumber}}</h6>
				<div>{{order.price}}
					euros</div>
				<div>{{order.status}}</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<h6>Adresse de livraison</h6>
					<div>
						<div>{{ order.shippingAddress.name}}</div>
						<div>{{ order.shippingAddress.streetName}}</div>
						<div>{{ order.shippingAddress.zipCode}}
							{{ order.shippingAddress.city}}</div>
						<div>{{ order.shippingAddress.country}}</div>
					</div>
				</div>
				<div class="col-md-6">
					<h6>Adresse de facturation</h6>
					<div>
						<div>{{ order.billingAddress.name}}</div>
						<div>{{ order.billingAddress.streetName}}</div>
						<div>{{ order.billingAddress.zipCode}}
							{{ order.billingAddress.city}}</div>
						<div>{{ order.billingAddress.country}}</div>
					</div>
				</div>
			</div>
			<a  href="#collapse-{{order.id}}" role="button" aria-expanded="false" aria-controls="collapse-{{order.id}}" data-toggle="collapse" data-target="#collapse-{{order.id}}" class="btn form-control">
				<i class="fas fa-chevron-down"></i>
			</a>
			<hr/>
			<div class="" id="collapse-{{order.id}}">
				<h6>Détails de la commande</h6>
				{% for orderProduct in order.orderProduct %}
					<div class="row">
						<div class="col-md-2" style="height:auto">
							<img class=" border rounded m-1" style=" width:100%" src="/images/products/{{orderProduct.product.picture.name}}">
						</div>
						<div class="col-md-10">
							<h6>{{orderProduct.product.name}}
							</h6>
							<div>{{orderProduct.product.description}}
							</div>
							<div>Quantité :
								{{orderProduct.quantity}}
							</div>
							<div>
								prix du lot:
								{{orderProduct.price}}
								euros</div>
						</div>
					</div>
					<hr/>
				{% endfor %}
			</div>
		</div>
	{% endfor %}

{% endblock %}

templates/order/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Order{% endblock %}

{% block body %}
    <h1>Edit Order</h1>

    {{ include('order/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('order_index') }}">back to list</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}

templates/order/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order index{% endblock %}

{% block body %}
    <h1>Order index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Code_number</th>
                <th>Price</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>
                <td>{{ order.id }}</td>
                <td>{{ order.codeNumber }}</td>
                <td>{{ order.price }}</td>
                <td>
                    <a href="{{ path('order_show', {'id': order.id}) }}">show</a>
                    <a href="{{ path('order_edit', {'id': order.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('order_new') }}">Create new</a>
{% endblock %}

templates/order/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Order{% endblock %}

{% block body %}
    <h1>Create new Order</h1>

    {{ include('order/_form.html.twig') }}

    <a href="{{ path('order_index') }}">back to list</a>
{% endblock %}

templates/order/order_as_seller.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order
{% endblock %}

{% block body %}
	<h1>Mes commandes
	</h1>
	{% for order in orders %}
		<div class="card p-3 mb-2 border rounded border-dark">
			<div class="mb-3">
				<h6>Commande n°{{ order.codeNumber}}</h6>
				<div>{{order.price}}
					euros</div>
				<div>
					{{ include('order/_change_status_form.html.twig') }}</div>
			</div>
			<div class="row">
				<div class="col-md-6">
					<h6>Adresse de livraison</h6>
					<div>
						<div>{{ order.shippingAddress.name}}</div>
						<div>{{ order.shippingAddress.streetName}}</div>
						<div>{{ order.shippingAddress.zipCode}}
							{{ order.shippingAddress.city}}</div>
						<div>{{ order.shippingAddress.country}}</div>
					</div>
				</div>
				<div class="col-md-6">
					<h6>Adresse de facturation</h6>
					<div>
						<div>{{ order.billingAddress.name}}</div>
						<div>{{ order.billingAddress.streetName}}</div>
						<div>{{ order.billingAddress.zipCode}}
							{{ order.billingAddress.city}}</div>
						<div>{{ order.billingAddress.country}}</div>
					</div>
				</div>
			</div>
			<a href="#collapse-{{order.id}}" role="button" aria-expanded="false" aria-controls="collapse-{{order.id}}" data-toggle="collapse" data-target="#collapse-{{order.id}}" class="btn form-control">
				<i class="fas fa-chevron-down"></i>
			</a>
			<hr/>
			<div class="" id="collapse-{{order.id}}">
				<h6>Détails de la commande</h6>
				{% for orderProduct in order.orderProduct %}
					<div class="row">
						<div class="col-md-2" style="height:auto">
							<img class=" border rounded m-1" style=" width:100%" src="/images/products/{{orderProduct.product.picture.name}}">
						</div>
						<div class="col-md-10">
							<h6>{{orderProduct.product.name}}
							</h6>
							<div>{{orderProduct.product.description}}
							</div>
							<div>Quantité :
								{{orderProduct.quantity}}
							</div>
							<div>
								prix du lot:
								{{orderProduct.price}}
								euros</div>
						</div>
					</div>
					<hr/>
				{% endfor %}
			</div>
		</div>
	{% endfor %}

{% endblock %}

templates/order/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Order{% endblock %}

{% block body %}
    <h1>Order</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>Code_number</th>
                <td>{{ order.codeNumber }}</td>
            </tr>
            <tr>
                <th>Price</th>
                <td>{{ order.price }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('order_index') }}">back to list</a>

    <a href="{{ path('order_edit', {'id': order.id}) }}">edit</a>

    {{ include('order/_delete_form.html.twig') }}
{% endblock %}